language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - python -m pytest
