version: "3.7"

# How to run: `$ docker-compose -f docker-compose-db-only.yml --env-file .env.compose up --remove-orphans`

services:
  postgresdb:
    container_name: login_postgresdb
    restart: unless-stopped
    image: postgres:12
#    volumes:
#      - ./data/postgresdb_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env.compose
    ports:
      - "${EXPOSED_DEFAULT_DATABASE_PORT}:${DEFAULT_DATABASE_PORT}"
    networks:
      - loginapp_database

  pgadmin:
    container_name: login_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#       - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresdb
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - loginapp_database
    restart: unless-stopped

  # Ref: https://github.com/bitnami/bitnami-docker-redis/blob/master/docker-compose-replicaset.yml
  redis-primary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${EXT_REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
#    volumes:
#      - ./data/redis:/bitnami/redis/data
    networks:
      - loginapp_database

  redis-secondary:
    image: docker.io/bitnami/redis:6.2
#    ports:
#      - 6380:6379
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary.loginapp_database
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${EXT_REDIS_PASSWORD}
      - REDIS_PASSWORD=${EXT_REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - loginapp_database

networks:
  loginapp:
    name: loginapp
  loginapp_database:
    name: loginapp_database