version: "3.7"

# How to run: `$ docker-compose --env-file .env.compose up --remove-orphans --build`
# FYI: to avoid always re-building the api-service, you may remove `--build` part

services:
  postgresdb:
    container_name: login_postgresdb
    restart: unless-stopped
    image: postgres:12
#    volumes:
#      - ./data/postgresdb_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env.compose
    ports:
      - "${EXPOSED_DEFAULT_DATABASE_PORT}:${DEFAULT_DATABASE_PORT}"
    networks:
      - loginapp_database

  pgadmin:
    container_name: login_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#       - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresdb
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - loginapp_database
    restart: unless-stopped

  api_service:
    container_name: login_api_service
    image: ardihikaru/fapi1:test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgresdb
    env_file:
      - .env.compose
    ports:
      # dockerize api-service exposes port 8001, while the native version will utilize post 8000
      # in this case, it will allow both services to run on the same time. :)
      - 8001:80
    networks:
      - loginapp
      - loginapp_database

networks:
  loginapp:
    name: loginapp
  loginapp_database:
    name: loginapp_database