version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#
# How to run: `$ docker-compose --env-file .env.compose up --remove-orphans`

services:
  postgresdb:
    container_name: login_postgresdb
    restart: unless-stopped
    image: postgres:12
#    volumes:
#      - ./data/postgresdb_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env.compose
    ports:
      - "${EXPOSED_DEFAULT_DATABASE_PORT}:${DEFAULT_DATABASE_PORT}"
    networks:
      - database

  test_postgresdb:
    container_name: login_test_postgresdb
    restart: unless-stopped
    image: postgres:12
#    volumes:
#      - ./data/test_postgresdb_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TEST_DATABASE_DB}
      - POSTGRES_USER=${TEST_DATABASE_USER}
      - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
    env_file:
      - .env.compose
    ports:
      - "${EXPOSED_TEST_DATABASE_PORT}:${TEST_DATABASE_PORT}"
    networks:
      - database

  pgadmin:
    container_name: login_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - database
    restart: unless-stopped

  api_service:
    container_name: login_api_service
    image: ardihikaru/fapi1:test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgresdb
      - test_postgresdb
    env_file:
      - .env.compose
    ports:
      - 8001:80
    networks:
      - loginapp
      - database

networks:
  app:
    name: loginapp
  database:
    name: database